- client/src/components/header/header.ts
- client/src/interfaces/Component.ts
- client/src/models/Canlendar.ts
- client/src/models/Observer.ts
Observer Pattern 적용을 위한 베이스 코드입니다.
@HanCheo
> chore: Base Code for Observer Pattern

- server/app.ts
- server/package-lock.json
- server/package.json
- server/src/api/index.ts
- server/src/app.ts
- server/src/config/webpack.config.js
- server/tsconfig.json
#11 
최대한 프로젝트에 익숙함을 위해 deal-5 프로젝트를 참고해서 expressjs를 작성했습니다.
express generator typescript는 구조가 좀 신뢰가지 않아서 [견고한 노드JS 서버](https://softwareontheroad.com/ideal-nodejs-project-structure/#folder)를 토대로 디렉토리 구조를 가져갔습니다.
```
src
│   app.js          # App entry point
└───api             # Express route controllers for all the endpoints of the app
└───config          # Environment variables and configuration related stuff
└───jobs            # Jobs definitions for agenda.js
└───loaders         # Split the startup process into modules
└───models          # Database models
└───services        # All the business logic is here
└───subscribers     # Event handlers for async task
└───types           # Type declaration files (d.ts) for Typescript
```
- 디렉토리 구조 생성
- 번들링 후 배포를 위한 webpack 추가. package.json 속에 …
> [BE] Express 서버 세팅 작업

- client/package-lock.json
- client/package.json
- client/src/assets/svg.ts
- client/src/components/MonthPicker.ts
- client/src/components/header/header.scss
- client/src/components/header/header.ts
- client/src/components/header/index.scss
- client/src/components/header/index.ts
- client/src/global.scss
- client/src/utils/calender.ts
- client/webpack.config.js
#4
헤더 리팩토링 위주의 기능추가
1. 디자인의 svg파일 추가
2. 태블릿 max-width 추가
3. 헤더 리팩토링
1. MonthPicker 따로 빼기
2. MonthPicker Observer 연결
3. 헤더의 좌우 arrow 기능 구현
4. 페이지 전환을 위한 아이콘 버튼 기능 구현
5. MonthPicker Backdrop 기능 구현
> [#4] feat : monthPicker 추가

- client/src/index.ts
#4
index에서 header import 하는부분 코드 오류
client index에서 header import 하는부분 코드 오류 수정
> [#4] fix : Header Import 수정

- .gitignore
- server/package-lock.json
- server/package.json
- server/src/app.ts
- server/src/config/sequelize-mysql.yaml
- server/src/config/sequelize-sqlite.yaml
- server/src/models/Account/AbstractAccountsStore.ts
- server/src/models/Account/Account.ts
- server/src/models/Account/account-sequelize.ts
- server/src/models/sequlze.ts
Sequelize 를 이용한 ORM 세팅
SQLite3 를 이용해서 우선 테스트를 하도록 했습니다. `sequelize-sqlite.yaml`를 이용해서 설정할 수 있도록 해놨습니다.
데이터 베이스 설정 파일의 경로를 나타내는 환경변수(`SEQUELIZE_CONNECT`) 를 통해 DB를 변경할 수 있도록 해놨습니다.
우선 Sequelize 기본 튜토리얼 기반으로 최대한 설정을 해봤습니다.
OAuth에 알맞는 모델링이 필요할 것 같습니다.
> feat: Sequelize 세팅과 간단한 설정

- client/src/components/header/index.scss
- client/src/components/header/index.ts
- client/src/core/Component.ts
- client/src/core/router.ts
- client/src/index.ts
- client/src/utils/customEvent.ts
#29
해시 라우팅 -> 히스토리 라우팅으로 방식 변경
componet interface 내용추가
route.ts 내용변경
Header component 사용예시 작성되어 있어요 :)
> [#29] refactor : Routing 처리 방식 변경

- client/src/components/Header/index.scss
- client/src/components/Header/index.ts
- client/src/components/LedgerAddButton/index.scss
- client/src/components/LedgerAddButton/index.ts
- client/src/components/LedgerAddModal/CategorySelector/index.scss
- client/src/components/LedgerAddModal/CategorySelector/index.ts
- client/src/components/LedgerAddModal/index.scss
- client/src/components/LedgerAddModal/index.ts
- client/src/components/LedgerContainer/index.ts
- client/src/components/LedgerItem/index.ts
- client/src/components/LedgerList/index.ts
- client/src/core/Component.ts
- client/src/interfaces/Category.ts
- client/src/interfaces/Ledger.ts
- client/src/pages/MainPage/index.scss
- client/src/pages/MainPage/index.ts
- client/src/pages/StatisticPage/index.ts
#22 
개발 단위가 커지는 듯해서 단계적으로 나눠서 PR올리려 합니다.
Main 화면에서 Ledger를 추가하는 모달을 구현 중입니다.
현재 모달을 컴포넌트로 생성해놨습니다.
- 대략적이 모달 컴포넌트의 형태 구현
- Category List를 드롭다운으로 선택할 수 있도록 구현했습니다. (내부적인 디자인은 수정 필요)
- Component 형태를 전적으로 수정 했습니다.
7bd68ec
위 커밋을 한번 참조해주세요. 기존에 만드신 것도 전부 Typesafety하게 적용했습니다. 이제부터 컴포넌트 만드실 때
`IState`와 `IProps`를 정의해서 아래와 같이 Component에 적용하면 훨씬 개발이 수월할 것 같습니다.
@HanCheo 
- 각 Input에 알맞은 입력 방법 구현하기
- datetime은 date picker 활용할 예정
- 결제 수단 선택은 카드를 원형에서 뽑듯한 효과
> [#22]feat: ledger 입력 모달 개발 + TypeSafety한 Component 적용(Generic으로 State, Prop Interface 받도록 수정)

- client/src/components/Header/index.ts
- client/src/components/LedgerContainer/index.scss
- client/src/components/LedgerContainer/index.ts
- client/src/components/LedgerItem/index.ts
- client/src/components/LedgerList/index.scss
- client/src/components/LedgerList/index.ts
- client/src/components/MonthPicker.ts
- client/src/components/SnackBar/index.scss
- client/src/components/SnackBar/index.ts
- client/src/global.scss
- client/src/index.ts
- client/src/interfaces/Ledger.ts
- client/src/models/Ledgers.ts
- client/src/utils/codeHelper.ts
#29
LedgerBody기능 구현 완료..?
1. 스낵바 추가
2. /*html*/ 형태가 불편하여 util helper 함수에 html을 추가함
- html`` 형태로 사용하심 됩니다.
3. sibling 형제노드 찾아주는 함수 추가
4. Ledger 옵저버 추가
5. blance 변수명 -> amout로 변경
6. 헤더 페이지별 아이콘 강조 추가
> [#29] feat : LedgerBody 구현

- client/src/assets/svg.ts
- client/src/components/Calendar/index.scss
- client/src/components/Calendar/index.ts
- client/src/components/Header/index.ts
- client/src/components/MonthPicker.ts
- client/src/components/SnackBar/index.ts
- client/src/index.ts
- client/src/models/Calendar.ts
- client/src/pages/CalendarPage/index.scss
- client/src/pages/CalendarPage/index.ts
- client/src/pages/index.ts
- client/src/utils/calendar.ts
#6
캘린더 UI 페이지 추가
1. 스낵바가 있을경우 새로운 스낵바 생성 방지
2. 캘린더 오타 수정
1. 요일별 가계부 추가 필요
2. 월 전환시 캘린더 변화 필요
> [#6] feat : 캘린더 UI 추가

- client/src/components/Calendar/index.scss
- client/src/components/Calendar/index.ts
- client/src/components/LedgerContainer/index.ts
- client/src/components/LedgerItem/index.ts
- client/src/components/LedgerList/index.ts
- client/src/pages/CalendarPage/index.scss
- client/src/utils/codeHelper.ts
#7
캘린더 Ledger Data 접근 및 UI 개선
1. Snackbar 오류 수정
2. Ledger가 있는 요일 데이터 확인
> [#7] feat : 캘린더 Ledger Data 접근 및 UI 개선

- client/src/components/Header/index.scss
- client/src/components/LedgerAddModal/CardTypeSelector/index.scss
- client/src/components/LedgerAddModal/index.scss
- client/src/global.scss
- client/src/pages/StatisticPage/index.scss
global max-width 수정
phone-max-width 추가
table  -> tablet 으로 수정
> style : max-width 수정

- client/src/components/Calendar/index.scss
- client/src/components/Header/index.scss
- client/src/global.scss
다크모드 색상 추가
색상코드 변경 및 background 
$off-white -> $background 수정
해더 배경색 제거
텍스트 색상은 변경하지 않으셔두 됩니다.
background만 좀 수정 해주심 될듯 해용
그리구 input date타입의 경우 color : inherit 해줌 되는데
오른쪽 icon 색상이 안바뀌네요...ㅠㅠ
> style : 다크모드 색상변경

- client/src/global.scss
다크모드 라이트모드 폰트 자동 변경
Month Picker 배경색 수정
> style : global style 수정

- client/src/components/Calendar/index.scss
- client/src/components/Header/index.scss
- client/src/components/Header/index.ts
- client/src/components/LedgerContainer/index.scss
- client/src/components/MonthPicker.ts
- client/src/global.scss
- client/src/models/Calendar.ts
#44
헤더 날짜 변경되도록 기능 추가
각 스타일변경
캘린더 모델 : prevMonth, nextMonth 함수 추가
헤더 - 하단 padding 줄임
Monthpicker - background 테마에 맞게 변경
LedgerContainer - 전체 갯수 색상변경
Calender - box shadow 윗부분 구분되도록 변경
> [#44] feat : 날짜 관련 컴포넌트 옵저버 Subscription 기능 추가

- client/src/components/LedgerAddButton/index.scss
- client/src/components/LedgerAddModal/CardTypeSelector/index.scss
- client/src/components/LedgerAddModal/CardTypeSelector/index.ts
- client/src/components/LedgerAddModal/CategorySelector/index.scss
- client/src/components/LedgerAddModal/CategorySelector/index.ts
- client/src/components/LedgerAddModal/index.scss
- client/src/components/LedgerAddModal/index.ts
- client/src/pages/WalletPage/index.scss
- client/src/pages/WalletPage/index.ts
Modal 관련해서 모바일 사이즈에서 UX상 이상한 부분들을 수정했습니다.
- padding, margin 값 수정이 대부분입니다.
@HanCheo
> chore: Modal 관련 Style 수정

- server/src/controllers/user.controller.ts
#52
프론트 cors 오류 수정
res 2번보내서 나타나는 오류 및 env 파일 수정
env 파일에서 CLIENT_URL 부분의 마지막 '/' 부분 지워주셔야 될 것 같습니당...
> [#52] fix : cors 오류 수정

- client/src/index.html
- server/src/controllers/ledger.controller.ts
- server/src/models/ledger.model.ts
- server/src/repositories/ledger.repository.ts
- server/src/router/index.ts
- server/src/router/ledger.router.ts
- server/src/services/ledger.service.ts
#61
ledger 데이터 조회용 api 개발
api 추가 !
이슈 참고옹
> [#61] feat: userLedgersByMonth api추가

- server/src/controllers/auth.controller.ts
- server/src/middleware/auth.middleware.ts
- server/src/models/user.model.ts
- server/src/repositories/user.repository.ts
- server/src/services/jwt.service.ts
- server/src/services/user.service.ts
#63
원활한 로그인 상태를 유지시키기 위한
JWT 리프레시 토큰 기능 구현
유저테이블 컬럼 리프레시 토큰 추가 변경
JWT 미들웨어 처리방식 변경
> [#63] feat: 리프레시 토큰 추가

- server/src/controllers/auth.controller.ts
- server/src/controllers/category.controller.ts
- server/src/controllers/ledger.controller.ts
- server/src/controllers/user.controller.ts
- server/src/repositories/category.repository.ts
- server/src/router/category.router.ts
- server/src/router/index.ts
- server/src/services/category.service.ts
- server/src/utils/HttpStatus.ts
Category 관련 Controller, Service, Repository, DTO 구현을 했습니다.
Category API
- `GET /api/category/`
모든 카테고리 조회 카테고리 Ledger List를 보여주는 모달에서 사용할 REST API
- `GET /api/category/1/`
테스트 및 카테고리 검증에 사용. 실제 어플리케이션에 사용하지는 않지만 확인용으로 사용될 예정.
- `category.router.ts`
- `category.controller.ts`
- `category.service.ts`
- `category.repository.ts`
카테고리 관련 모든 Layer들이 추가됐습니다.
~~category.service의 getCategory method는 Ledger 추가될 때, category ID가 유효한지 검사하는데 사용될 예정입니다.~~ 완료
`LedgerController.createLedger` 파라미터 검증 코드를 추가 반영했습니다.
> [#68] Category 관련 Controller, Service, Repository 구현 

- server/src/controllers/category.controller.ts
- server/src/controllers/ledger.controller.ts
- server/src/controllers/paymentType.controller.ts
- server/src/dto/CategoryDTO.ts
- server/src/dto/LedgerDTO.ts
- server/src/dto/PaymentTypeDTO.ts
- server/src/loaders/sequelize.loaders.ts
- server/src/middleware/auth.middleware.ts
- server/src/models/index.ts
- server/src/models/init_data.ts
- server/src/models/ledger.model.ts
- server/src/models/paymenttype.model.ts
- server/src/models/user.model.ts
- server/src/repositories/category.repository.ts
- server/src/repositories/ledger.repository.ts
- server/src/repositories/paymentType.repository.ts
- server/src/repositories/user.repository.ts
- server/src/router/category.router.ts
- server/src/router/index.ts
- server/src/router/ledger.router.ts
- server/src/router/paymentType.router.ts
- server/src/services/category.service.ts
- server/src/services/ledger.service.ts
- server/src/services/paymentType.service.ts
#67 
Payment Type 데이터와 관련된 REST API들을 구현했습니다. [API 정리 WIKI](https://github.com/woowa-techcamp-2021/cashbook-5/wiki/PaymentType-%EA%B4%80%EB%A0%A8-REST-API)
- `GET /api/paymentType/` 
- `POST /api/paymentType/`
- `DELETE /api/paymentType/`
에러처리에 기준이 필요한 것 같아 한번 정리놓겠습니다.
- `Error`(`try...catch`)로 처리하는 것은 예상하지 못한 에러(실제 데이터 베이스 문제, 일관성이 지켜지지않는 문제)에 대비하기 위해 사용.
- 그 외에 사용자의 parameter 실수 혹은 유효하지 않은 데이터를 넣었을 때 경고를 주는 것들은 null check, boolean check로 처리
- `Controller` Layer 에서 Error Message는 상수화해서 처리한다.
- `Repository` or `Service` Layer에서는 자세한 Error Message를 생성해서 올려보내주거나 콘솔로 남긴다.
User Repository 의 코드 스타일을 수정해야할 것 같습니다. `UserAttribute` 사용을 지양하고 User 타입을 사용해서 User를 DTO로 매핑하는 형태로 변경할 필요가 있어보입니다.
> [#67] PaymentType 관련 Controller, Service, Repository 생성

- server/src/controllers/ledger.controller.ts
- server/src/dto/LedgerDTO.ts
- server/src/models/category.model.ts
- server/src/models/ledger.model.ts
- server/src/repositories/ledger.repository.ts
- server/src/router/ledger.router.ts
- server/src/services/ledger.service.ts
[#71] [#83]
메인, 캘린더용 ledger 조회 api 추가
기존 ledger 조회 api 에서 서버에서 일자별로 
데이터 새롭게 전처리하는 방식으로 수정
위에 따른 백엔드 ledgers date 타입 Date -> string 변경
> [#71] Ledgers data Type 변경

- client/src/api/ledgerAPI.ts
- client/src/components/Calendar/index.ts
- client/src/components/Header/index.ts
- client/src/components/LedgerContainer/index.ts
- client/src/components/LedgerItem/index.ts
- client/src/components/LedgerList/index.ts
- client/src/core/Component.ts
- client/src/interfaces/Ledger.ts
- client/src/models/Ledgers.ts
- client/src/models/Observer.ts
- client/src/pages/CalendarPage/index.ts
- client/src/pages/MainPage/index.ts
- client/src/utils/calendar.ts
#83
메인, 캘린더용 ledger API 개발
1. 컴포넌트, 옵저버 형식 변경
2. subscribe 되는 컴포넌트 unmount 추가
3. ledger api의 데이터에 따른 코드리팩토링
> [#83] feat : ledger API에 따른 프론트 코드 refactor

- client/src/api/fetch.ts
- client/src/api/statisticAPI.ts
- client/src/pages/StatisticPage/index.ts
- server/src/controllers/ledger.controller.ts
- server/src/db/sequlze.ts
- server/src/dto/LedgerDTO.ts
- server/src/repositories/ledger.repository.ts
- server/src/router/ledger.router.ts
- server/src/services/ledger.service.ts
#76 
통계 그래프(라인차트, 파이차트)를 위한 category 그룹 데이터를 응답해주는 API를 설계했습니다.
`GET /api/ledger/statistic?date="2021-08"`
- Response
```
{
"success": true,
"data": {
"보험": {
"total": "000000",
"color": "#e6d267",
"entries": [
{
"datetime": "2021-08-02T00:00:00.000Z",
"amount": "0"
},
{
"datetime": "2021-08-02T00:00:00.000Z",
"amount": "0"
},
{
"datetime": "2021-08-02T00:00:00.000Z",
"amount": "0"
},
{
"datetime": "2021-08-02T00:00:00.000Z",
"amount": "0"
},
{
"datetime": "2021-08-02T00:00:00.000Z",
"amount": "0"
}
]
},
"적금": {
"total": "00",
"color": "#6ed5eb",
"entries": [
{
"datetime": "2021-08-02T00:00:00.000Z",
"amount": "0"
}
]
},
"예금": {
"total": "00",
"color": "#4cb8b8",
"entries": [
{
"datetime": "2021-08-02T00:00:00.000Z",
"amount": "0"
}
]
},
"주식": {
"total": "003000300030003000",
"color": …
```
> [#76] 통계 그래프를 그리기위한 데이터 조회 API  구현과 FE 연결작업

- client/src/api/loginAPI.ts
- client/src/components/LoginModal/index.ts
- server/src/controllers/auth.controller.ts
- server/src/router/auth.router.ts
#91
깃허브 로그인 url 서버에서 관리할수 있도록 변경
url을 가져오는 api추가
> [#91] fix : 로그인 버튼 클릭시 href url 서버에서 가져오는 형태로 변경

- client/src/api/fetch.ts
- client/src/api/ledgerAPI.ts
- client/src/api/loginAPI.ts
- client/src/api/paymentTypeAPI.ts
- client/src/components/LedgerAddModal/CardTypeSelector/index.ts
- client/src/components/LedgerAddModal/index.ts
- client/src/components/LoginModal/index.ts
- client/src/components/PaymentTypeAddModal/index.scss
- client/src/components/PaymentTypeAddModal/index.ts
- client/src/interfaces/CardType.ts
- client/src/models/PaymentTypeList.ts
- client/src/pages/WalletPage/index.scss
- client/src/pages/WalletPage/index.ts
- server/src/controllers/paymentType.controller.ts
#78 
My Wallet Page 기능 구현 완성
- 결제수단 추가하기
- 현재 결제수단 리스트 보여주기
- 현재 결제수단 삭제하기(alert 모달은 아직 미구현)
Login Page 에 OAuth Resource 서버 링크가 변경되었습니다. 한철님이 작업하신 PR이후로는 동적인 OAuth 링크 처리가 가능하니 우선 제 github oauth link를 개발용으로 사용하고 있겠습니다.
>  [#78] My Wallet Page 기능 완성(API 구현 및 모달 추가)

- server/src/controllers/user.controller.ts
- server/src/db/sequlze.ts
- server/src/repositories/user.repository.ts
> feat: 배포용 백엔드 수정

- client/src/components/LedgerAddModal/index.ts
금액을 입력하는 Input에 1억 이상 값이 들어가면 SnackBar로 알려주고 금액은 1억으로 바꾸는 기능 추가했습니다. 
코드가 짧아서 특별한 내용은 작성하지않겠습니다. @HanCheo
> [#101] Amount 입력 Input 범위 제한시키기 (스낵바를 이용해서 사용자에게 전달)

- client/src/pages/StatisticPage/CategoryList/index.ts
- client/src/pages/StatisticPage/index.scss
- client/src/pages/WalletPage/index.scss
- client/src/utils/charts/LineChart.ts
통계 화면과 My Wallet 화면에서 부족했던 반응성을 개선했습니다.
주로 Media query 사용한 css 작업입니다.
> 통계 차트와 My Wallet 페이지 반응형 개선 

- client/src/api/fetch.ts
- client/src/api/ledgerAPI.ts
- client/src/components/LedgerAddModal/index.ts
- client/src/components/LedgerContainer/index.ts
- client/src/components/LedgerItem/index.ts
- client/src/interfaces/Ledger.ts
- client/src/pages/MainPage/index.ts
#75
api연동하여 수정기능 추가했습니다
1. addmodal에 ledger데이터가 props로 넘어왔는지 아닌지 체크하여 수정/추가로 변경
2. api 추가
ledgerContainer 부분에 
ledgerEditButtonClickHandler 참고해서 연결만 하면됩니다.
edit랑 같이 만들면서 해서 deleteLedgerData API도 이써용
정말로 삭제할까요? 같은 alert 화면도 있으면 좋을듯 해용 !
> [#75] feat : 가계부 수정기능추가

- client/src/components/Header/index.scss
- client/src/components/Header/index.ts
- client/src/components/LedgerAddModal/CategorySelector/index.scss
- client/src/components/LedgerAddModal/index.scss
- client/src/components/LedgerAddModal/index.ts
- client/src/components/LedgerContainer/index.scss
- client/src/components/LedgerContainer/index.ts
- client/src/components/LedgerItem/index.ts
- client/src/components/LedgerList/index.ts
에잇 ui 변경 ~
1. 헤더 날짜 변경 ui 수정
2. 전체 건수 못가져올때 발생하는 오류 수정
3. addModal ui 수정
4. 가게부 수정시 상단에 가계부 수정 div 추가
> [#113] style : 헤더, 메인, addModal ui 수정

- client/src/components/Header/index.scss
- client/src/components/Header/index.ts
- client/src/components/LedgerContainer/index.ts
- client/src/components/SnackBar/index.scss
- client/src/global.scss
- client/src/index.html
- client/src/pages/StatisticPage/CategoryList/index.scss
- client/src/pages/StatisticPage/CategoryList/index.ts
- client/src/pages/StatisticPage/index.ts
헤더의 왼쪽 문구 메인으로 라우팅 될수 있도록 변경
1. 라우팅 추가
2. UI 수정
> feat : UI 수정 

- client/src/components/Header/index.ts
> fix : git 아바타 클릭시 라우팅 안되는 오류 수정

- deploy.sh
크론탭에서 실행되는 스크립트의 시작경로 이상으로 제대로 스크립트가 실행되지않는 버그 수정.
> 배포 스크립트 수정

- server/src/repositories/ledger.repository.ts
- server/src/repositories/paymentType.repository.ts
- server/src/repositories/user.repository.ts
#126
원활한 테스트 진행을 위한 기본 데이터 추가
유저 최초 생성시 데이터 init 해주는 함수 및 내용 추가
문구 = [
'안녕하세요 :)',
'이건 데모 및 테스트용 데이터 입니다.',
'유저를 생성할때 자동으로 만들어지며',
'좀더 원활한 테스트 진행을 위해 만들어졌습니다.',
'재미있게 구경해주세요 :)',
'시퀄라이저를 사용하였는데 다른 OMR에 비해 코딩할 내용이 많은것 같습니다.',
'옵션으로 항상 추가해주어야 하는 부분도 있고',
'생각보다 옵션이 많아서 계속 찾게되는 경향이 있었습니다.',
'트랜잭션을 키면 왜 쿼리에 옵션으로 넣어 연결해야하는지도 잘 모르겠습니다.',
'자료가 많은 이유가 이러한 이유지 않을까 싶습니다.',
'다음부터는 다른 ORM을 사용할 계획입니다. :)',
]
> [#126] feat : 최초 회원가입시 기본데이터 추가
